### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by jahway603** [Peergos/packaging#1]
Was going to start to package this for the Arch Linux AUR repository. The PKGBUILD I've written in the past typically pull down a tar.gz of the release from a git repo and then uses that.

Any suggestions on how to automate the pulling of the latest Peergos release with the https://peergos.net/public/peergos/releases link?

Or is it possible that someone at Peergos could release tar.gz releases here on Github or another git platform?

**Comment by ianopolous** [comment]
Yes we will start tagging and releasing on github as well. 

Note that the released jars are built from the web-ui repo (which has the peergos repo as a submodule).

**Comment by jahway603** [comment]
So the released jars would be [here](https://github.com/Peergos/web-ui/releases) in the future then?

**Comment by ianopolous** [comment]
Yep, and we plan on doing one quite soon.

**Comment by ianopolous** [comment]
That repo also builds native static binaries if you prefer those.

**Comment by ianopolous** [comment]
We've just done the next release: https://github.com/Peergos/web-ui/releases/tag/v0.8.0

**Comment by jahway603** [comment]
Package now up on AUR. I noticed that both the webui and peergos have different licenses, so this package pulls down both.

```
$ paru peergos
1 aur/peergos 0.8.0-1 [+0 ~0.00] [Installed]
    A p2p, secure file storage, social network and application protocol
:: Packages to install (eg: 1 2 3, 1-3):
:: 
```
